  
sudo: false

language: node_js

node_js:

  - "12.9.0"

install:

- npm install

script:

  - "npm test"

after_success:

  - "npm run coveralls"

before_script:

  - psql -c 'create database travis_ci_test;' -U postgres
