  
sudo: false

language: node_js

node_js:

  - "12.9.0"

before_script:

  - psql -c 'CREATE DATABASE mydiary;' -U postgres

install:

- npm install

script:

  - "npm test"

after_success:

  - "npm run coveralls"
  