language: node_js

node_js:

  - "12.9.0"

before_script:

  - npm install

services:

- postgresql

before_script:

  - psql -c 'CREATE DATABASE mydiary;' -U postgres

script:

  - "npm test"

after_script:

  - "npm run coveralls"

notifications:

  email: false

sudo: false
  